version: '3'

services:
  db:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 27018:27017
    volumes:
      - .:/servers
      - db:/data/db
    networks:
      - app-network

  app:
    depends_on:
      - db
    build: ./servers
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27018
      - MONGOQUERYPARAMS=?authSource=admin
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge

volumes:
  db:
